#!/bin/bash

# curl https://raw.githubusercontent.com/mrowa44/dotfiles/master/install | bash

dotfiles="$HOME/dotfiles"

# Install Homebrew
which -s brew
if [[ $? != 0 ]] ; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Clone dotfiles
if [ ! -d $dotfiles ]; then
  cd $HOME
  git clone --recursive git@github.com:mrowa44/dotfiles.git
fi

cd $dotfiles
brew tap Homebrew/bundle
brew bundle

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd ~
ln -sf ${DIR}/zshrc .zshrc
ln -sf ${DIR}/zpreztorc .zpreztorc
ln -sf ${DIR}/zsh .zsh
ln -sf ${DIR}/vimrc .vimrc
ln -sf ${DIR}/vim .vim
ln -sf ${DIR}/gitconfig .gitconfig
ln -sf ${DIR}/gitignore .gitignore
ln -sf ${DIR}/tmux.conf .tmux.conf
ln -sf ${DIR}/psqlrc .psqlrc
ln -sf ${DIR}/ctags .ctags
ln -sf ${DIR}/agignore .agignore
ln -sf ${DIR}/gemrc .gemrc
ln -sf ${DIR}/eslintrc.js .eslintrc.js
ln -sf ${DIR}/my.cnf .my.cnf
cd $dotfiles

xcode-select --install
# rvm get stable --auto-dotfiles

# Enable filevault if it's not already
fdesetup status || sudo fdesetup enable

# chrome://flags/#enable-javascript-harmony
# chrome://flags/#automatic-tab-discarding
# https://www.amazon.com/gp/sendtokindle/mac

npm -g install eslint fast-cli yolo-cli csslint jsonlint sass-lint mocha
gem install tmuxinator
pip install howdoi flake8 pylint
