#!/bin/bash

# chsh -s `which zsh`
# git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf ${DIR}/zshrc ~/.zshrc
ln -sf ${DIR}/zpreztorc ~/.zpreztorc
ln -sf ${DIR}/zsh ~/.zsh
ln -sf ${DIR}/vimrc ~/.vimrc
ln -sf ${DIR}/vim ~/.vim
ln -sf ${DIR}/gitconfig ~/.gitconfig
ln -sf ${DIR}/gitignore ~/.gitignore
ln -sf ${DIR}/tmux.conf ~/.tmux.conf
ln -sf ${DIR}/psqlrc ~/.psqlrc
ln -sf ${DIR}/ctags ~/.ctags
ln -sf ${DIR}/agignore ~/.agignore
ln -sf ${DIR}/gemrc ~/.gemrc
ln -sf ${DIR}/eslintrc ~/.eslintrc
ln -sf ${DIR}/my.cnf ~/.my.cnf

brew install vim --override-system-vi

brew install\
  git\
  diff-so-fancy\
  ag\
  ctags\
  httpie\
  tig\
  node\
  tree\
  redis\
  nvm\
  ccat\
  postgresql

brew cask install\
  sequel-pro\
  postico\
  google-chrome\
  virtualbox\
  slack\
  spotify\
  flycut\
  caffeine\
  thyme
gem install rvm tmuxinator bundler
