#!/bin/bash

# http://brew.sh/

brew install vim --with-override-system-vi
brew install\
  ag\
  cask\
  ccat\
  ctags\
  diff-so-fancy\
  git\
  httpie\
  node\
  nvm\
  postgresql\
  progress\
  reattach-to-user-namespace\
  redis\
  tig\
  tmux\
  tree\
  watch\
  z

brew cask install\
  1password\
  caffeine\
  flycut\
  gimp\
  goofy\
  google-chrome\
  iterm2\
  postman\
  psequel\
  sequel-pro\
  slack\
  spotify\
  thyme\
  virtualbox\
  vlc

# if [ ! -d ~/dotfiles ]; then
#   (cd ~ && git clone https://github.com/mrowa44/dotfiles);
# fi

[ -d ~/Projects ] || mkdir ~/Projects

if [ $SHELL != /bin/zsh ]; then
  chsh -s `which zsh`
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ln -sf ${DIR}/zshrc ~/.zshrc
ln -sf ${DIR}/zpreztorc ~/.zpreztorc
ln -sf ${DIR}/zsh ~/.zsh
ln -sf ${DIR}/vimrc ~/.vimrc
ln -sf ${DIR}/vim ~/.vim
ln -sf ${DIR}/gitconfig ~/.gitconfig
ln -sf ${DIR}/gitignore ~/.gitignore
ln -sf ${DIR}/tmux.conf ~/.tmux.conf
ln -sf ${DIR}/psqlrc ~/.psqlrc
ln -sf ${DIR}/ctags ~/.ctags
ln -sf ${DIR}/agignore ~/.agignore
ln -sf ${DIR}/gemrc ~/.gemrc
ln -sf ${DIR}/eslintrc ~/.eslintrc
ln -sf ${DIR}/my.cnf ~/.my.cnf

# gem install rvm tmuxinator bundler
