#!/bin/bash

# chsh -s `which zsh`

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf ${DIR}/zshrc ~/.zshrc
ln -sf ${DIR}/zsh ~/.zsh
ln -sf ${DIR}/vimrc ~/.vimrc
ln -sf ${DIR}/vim ~/.vim
ln -sf ${DIR}/gitconfig ~/.gitconfig
ln -sf ${DIR}/gitignore ~/.gitignore
ln -sf ${DIR}/tmux.conf ~/.tmux.conf
ln -sf ${DIR}/psqlrc ~/.psqlrc
ln -sf ${DIR}/ctags ~/.ctags
ln -sf ${DIR}/agignore ~/.agignore
ln -sf ${DIR}/gemrc ~/.gemrc
ln -sf ${DIR}/eslintrc ~/.eslintrc
ln -sf ${DIR}/my.cnf ~/.my.cnf

# brew install git diff-so-fancy ag ctags httpie pandoc tig node tree redis
# brew install vim --override-system-vi
# brew cask install sequel-pro google-chrome
# gem install rvm tmuxinator
