#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'uri'

doistrc = File.expand_path('~') + '/.doistrc'
token = File.read(doistrc).chomp

uri = URI.parse("https://todoist.com/API/query?queries=[%22today%22,%22overdue%22]&token=#{token}")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
response = http.request(Net::HTTP::Get.new(uri.request_uri)).body
tasks_count = 0
JSON.parse(response).each { |item| tasks_count += item['data'].count }
if tasks_count > 0
  puts "#[fg=red]#{tasks_count}#[fg=default]"
else
  puts "#[fg=yellow]#{tasks_count}#[fg=default]"
end
